version: '3'
services:
  server:
    image: rhogoron:1.0
    build: .
    container_name: OneContainer

  proxy:
    image: nginx
    container_name: TwoContainer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
